# Generated by Django 3.1.2 on 2020-10-04 19:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 4, 19, 38, 31, 980773))),
                ('time', models.TimeField(default='19:38')),
                ('wet', models.BooleanField()),
                ('dirty', models.BooleanField()),
                ('leftside', models.IntegerField()),
                ('rightside', models.IntegerField()),
                ('sup_amount', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sup_f', models.BooleanField()),
                ('sup_b', models.BooleanField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='baby.baby')),
            ],
        ),
    ]
