# Generated by Django 3.1.2 on 2020-10-18 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201018_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babytrack',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 19, 42, 18, 129044)),
        ),
    ]
